# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42a93e076a7c513301b5deab0b2526b234f87c4acd27635322fd75af9d4c8489e65d412b9f6e4502680015cd104f06ff80d0c5b81d0259f67696f8a5ede8d665

test:
  secret_key_base: 34da62f08a8cad2510ad79db542fa764690af19496079cbfa82be250750a176995f5141ff6c5a38ec82855400f59aa687326863f132407c764a2d6937ea48c64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
